import type { BlueprintConfig } from "./config.js";
import type { TokenEntry } from "./tokens.js";
import { colorTokens } from "./tokens.js";

export function buildAgentRules(
  config: BlueprintConfig,
  tokenEntries: TokenEntry[]
): string {
  const colors = colorTokens(tokenEntries);
  const colorNames = colors.map((c) => c.name.replace(/^--color-/, ""));
  const tailwindHints = colorNames
    .slice(0, 8)
    .map((n) => `bg-${n}, text-${n}`)
    .join(", ");

  const stack = config.stack;
  const stackLine = [
    stack?.framework ?? "react",
    stack?.typescript ? "TypeScript" : null,
    stack?.tailwind ? "Tailwind" : null,
  ]
    .filter(Boolean)
    .join(" + ");

  return [
    "# Stryct blueprint (generated by stryct sync — edit stryct.config.ts then re-run sync)",
    "",
    `Stack: ${stackLine}.`,
    `Tokens file: ${config.paths.tokens}`,
    `Components: ${config.paths.components}/ only${config.paths.componentsUi ? ` (UI: ${config.paths.componentsUi}/)` : ""}.`,
    "",
    "Colors:",
    colorNames.length
      ? `- Use Tailwind utilities tied to tokens: ${tailwindHints}.`
      : "- Define colors in tokens.css as --color-*.",
    "- Do not add new raw #hex values in TSX or CSS.",
    "",
    "Spacing:",
    "- Prefer theme scale (px-4, gap-6), not arbitrary p-[13px].",
    "",
    "After editing tokens.css run: stryct export --tokens",
  ].join("\n");
}
